services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: camagru-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:z
    depends_on:
      - php
    networks:
      - camagru-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: camagru-php
    env_file:
      - .env
    volumes:
      - ./:/var/www/html:z
    networks:
      - camagru-network

  db:
    image: docker.io/library/mysql:8.0
    container_name: camagru-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - camagru-network

networks:
  camagru-network:
    driver: bridge

volumes:
  db_data:
